name: Template workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12.16.1-stretch
    steps:
      - uses: actions/checkout@v1

      - name: Tests
        env:
          NODE_ENV: 'test'
        run: |
          npm i
          npm test

  lint:
    runs-on: ubuntu-latest
    container:
      image: node:12.16.1-stretch
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: |
          npm i
          npm run lint

  audit:
    runs-on: ubuntu-latest
    container:
      image: node:12.16.1-stretch
    steps:
      - uses: actions/checkout@v1
      - name: Audit
        run: |
          npm install
          npm audit
